BEGIN TRANSACTION

IF @@TRANCOUNT = 1
	UPDATE	[dbo].[Mc_Action] 
	SET		[InstanceRequired] = 0
	WHERE	[ActionId] = 'BB0239EC-6259-4D7A-B392-FA22ED8FEF65';

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	UPDATE	[dbo].[Mc_Action] 
	SET		[InstanceRequired] = 0
	WHERE	[ActionId] = 'CD1EBE2B-C229-421C-847A-6FF560665D1A';

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
   COMMIT TRANSACTION
