BEGIN TRANSACTION

SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, QUOTED_IDENTIFIER, CONCAT_NULL_YIELDS_NULL, XACT_ABORT ON
SET NUMERIC_ROUNDABORT OFF

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	ALTER TABLE [dbo].[Mc_Action] DROP CONSTRAINT [FK_Mc_Action_Mc_Action]

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	DELETE FROM [dbo].[Mc_Action] WHERE [ActionId] = '0F6731D3-EE3A-4614-9092-043E088CC3F2'

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	DELETE FROM [dbo].[Mc_Action] WHERE [ActionId] = 'D934D126-F53A-49F0-833C-1C660EBC7894'

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1	
	ALTER TABLE [dbo].[Mc_Action] ADD CONSTRAINT [FK_Mc_Action_Mc_Action] FOREIGN KEY ([ParentActionId]) REFERENCES [dbo].[Mc_Action] ([ActionId])
	
IF @@ERROR <> 0
	IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	COMMIT TRANSACTION