BEGIN TRANSACTION

SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, QUOTED_IDENTIFIER, CONCAT_NULL_YIELDS_NULL, XACT_ABORT ON
SET NUMERIC_ROUNDABORT OFF

IF @@ERROR <> 0
	IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	UPDATE dbo.Mc_Action SET [ClassFullName] = N'Micajah.Common.Bll.Providers.ActionProvider' WHERE ActionId = 'A3223AB8-D9E7-437A-AE0E-14164C0F90B7'

IF @@ERROR <> 0
	IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	UPDATE dbo.Mc_Action SET [ClassFullName] = N'Micajah.Common.Bll.Providers.ActionProvider' WHERE ActionId = '14C1A008-D65D-40BB-BFF8-D077BA1DE995'

IF @@ERROR <> 0
	IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	UPDATE dbo.Mc_Action SET [ClassFullName] = N'Micajah.Common.Bll.Providers.ActionProvider' WHERE ActionId = 'F53C5189-BD4D-47E5-88EF-58B81178F7EF'

IF @@ERROR <> 0
	IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	UPDATE dbo.Mc_Action SET [ClassFullName] = N'Micajah.Common.Bll.Providers.ActionProvider' WHERE ActionId = '72B411D0-FB81-4444-B217-AFC4416A5319'

IF @@ERROR <> 0
	IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	UPDATE dbo.Mc_Action SET [ClassFullName] = N'Micajah.Common.Bll.Providers.ActionProvider' WHERE ActionId = '5749FF70-4592-4B91-8579-5E7E203C0410'

IF @@ERROR <> 0
	IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	COMMIT TRANSACTION
