<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" Inherits="MagicFormTestPage" Codebehind="MagicForm.aspx.cs" %>

<%@ MasterType TypeName="Micajah.Common.Pages.MasterPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageBody" runat="Server">
    <asp:PlaceHolder ID="SelectHolder" runat="server">Select a color scheme&nbsp;
        <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
        </asp:DropDownList>
        <br />
    </asp:PlaceHolder>
    <p>
        This is MagicForm control</p>
    <mits:MagicForm ObjectName="Organization" ID="MagicForm1" runat="server" AutoGenerateInsertButton="True"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DefaultMode="Edit"
        DataKeyNames="OrganizationId" AutoGenerateRows="false" RepeatColumns="1" DataSourceID="ObjectDataSource1"
        ShowCloseButtonSeparate="true" Width="550px" HeaderText="HeaderText" FooterText="FooterText">
        <CaptionControls>
            <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="http://www.google.com"
                Target="_blank" Text="Google search"></asp:HyperLink>
            <asp:LinkButton ID="ShowInactiveButton" runat="server" Text="Show Inactive" CausesValidation="false"
                OnClick="ShowInactiveButton_Click"></asp:LinkButton>
            <asp:LinkButton ID="ShowActiveButton" runat="server" Text="Show Active" CausesValidation="false"
                OnClick="ShowActiveButton_Click"></asp:LinkButton>
        </CaptionControls>
        <Fields>
            <mits:TextBoxField DataField="OrganizationId" HeaderText="Standard Form input" ReadOnly="true"
                ToolTip="A small description of the field" HeaderStyle-Width="120px">
            </mits:TextBoxField>
            <mits:TextBoxField DataField="Name" Required="true" HeaderText="Name">
            </mits:TextBoxField>
            <mits:TemplateField HeaderText="Name1">
                <ItemTemplate>
                    <asp:TextBox ID="Name1" runat="server" TextMode="MultiLine"></asp:TextBox>
                </ItemTemplate>
            </mits:TemplateField>
            <mits:TextBoxField DataField="Description" HeaderText="Description" TextMode="MultiLine"
                Required="true" EmptyText="Enter description here">
            </mits:TextBoxField>
            <mits:TextBoxField DataField="GraceDays" HeaderText="Grace Days" Required="true"
                ValidationErrorMessage="It should be integer number" ValidationType="Integer">
            </mits:TextBoxField>
            <mits:CheckBoxField DataField="Beta" HeaderText="Beta" Required="true">
            </mits:CheckBoxField>
            <mits:GroupField Text="Group 1">
            </mits:GroupField>
            <asp:CheckBoxField DataField="Trial" Text="This is a checkbox"></asp:CheckBoxField>
            <mits:TemplateField HeaderText="DropDown">
                <ItemTemplate>
                    <asp:DropDownList ID="ddl1" runat="server">
                        <asp:ListItem>Option 1</asp:ListItem>
                        <asp:ListItem>Option 2</asp:ListItem>
                    </asp:DropDownList>
                    Simple text inside form
                </ItemTemplate>
            </mits:TemplateField>
            <mits:TemplateField HeaderText="Radio button list">
                <ItemTemplate>
                    <asp:RadioButtonList ID="rbl1" runat="server">
                        <asp:ListItem>Option 1</asp:ListItem>
                        <asp:ListItem>Option 2</asp:ListItem>
                    </asp:RadioButtonList>
                </ItemTemplate>
            </mits:TemplateField>
            <mits:TemplateField HeaderText="Checkbox list">
                <ItemTemplate>
                    <asp:CheckBoxList ID="cbl1" runat="server">
                        <asp:ListItem>Option 1</asp:ListItem>
                        <asp:ListItem>Option 2</asp:ListItem>
                    </asp:CheckBoxList>
                    <small>A small description of the field</small>
                </ItemTemplate>
            </mits:TemplateField>
            <mits:GroupField Text="Group 2">
            </mits:GroupField>
            <mits:DatePickerField HeaderText="Date" Required="True" Type="Date" DataField="ExpirationTime">
            </mits:DatePickerField>
            <mits:DatePickerField HeaderText="DatePicker" Required="True" Type="DatePicker" DataField="ExpirationTime">
            </mits:DatePickerField>
            <mits:DatePickerField HeaderText="DateTime" Required="True" Type="DateTime" DataField="ExpirationTime">
            </mits:DatePickerField>
            <mits:DatePickerField HeaderText="DateTimePicker" Required="True" Type="DateTimePicker"
                DataField="ExpirationTime">
            </mits:DatePickerField>
            <mits:DatePickerField HeaderText="Time" Required="True" Type="Time" DataField="ExpirationTime">
            </mits:DatePickerField>
            <mits:DatePickerField HeaderText="TimePicker" Required="True" Type="TimePicker" DataField="ExpirationTime">
            </mits:DatePickerField>
        </Fields>
    </mits:MagicForm>
    <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" SelectMethod="GetOrganizations"
        TypeName="Micajah.Common.Bll.Providers.OrganizationProvider"></asp:ObjectDataSource>
    <p>
        &nbsp;</p>
    <hr />
    <p>
        This is Table control that looks like MagicForm
    </p>
    <asp:Table ID="Table1" runat="server" Width="550px">
        <asp:TableRow CssClass="Caption">
            <asp:TableCell ColumnSpan="2">
                <table cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                        <td>
                            <asp:Literal ID="Literal3" runat="server" Text="Edit Organization"></asp:Literal>
                        </td>
                        <td style="text-align: right;">
                            <asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="http://www.google.com"
                                Target="_blank" Text="Google search"></asp:HyperLink>&nbsp;
                            <asp:LinkButton ID="LinkButton8" runat="server" Text="Show Inactive" CausesValidation="false"
                                OnClick="ShowInactiveButton_Click"></asp:LinkButton>&nbsp;
                            <asp:LinkButton ID="LinkButton9" runat="server" Text="Show Active" CausesValidation="false"
                                OnClick="ShowActiveButton_Click"></asp:LinkButton>
                        </td>
                    </tr>
                </table>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow CssClass="Header">
            <asp:TableCell ColumnSpan="2">
                <asp:Literal ID="Literal4" runat="server" Text="HeaderText"></asp:Literal>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell Width="120px">
                <asp:Label ID="Label3" runat="server">Standard Form input</asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <mits:TextBox ID="txt1" runat="server" Required="true" Columns="35" ValidationGroup="Table1" />
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow CssClass="Group">
            <asp:TableCell ColumnSpan="2">
                            <div>Group 1</div>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
            </asp:TableCell>
            <asp:TableCell>
                <asp:CheckBox ID="chk1" runat="server" Text="This is a checkbox" />
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Label ID="ddl1lbl" runat="server">DropDown</asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:DropDownList ID="ddl1" runat="server" ValidationGroup="Table1">
                    <asp:ListItem>Option 1</asp:ListItem>
                    <asp:ListItem>Option 2</asp:ListItem>
                </asp:DropDownList>
                Simple text inside form
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Label ID="rbl1lbl" runat="server">Radio button list</asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:RadioButtonList ID="rbl1" runat="server" ValidationGroup="Table1">
                    <asp:ListItem>Option 1</asp:ListItem>
                    <asp:ListItem>Option 2</asp:ListItem>
                </asp:RadioButtonList>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Label ID="Label1" runat="server">Checkbox list</asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:CheckBoxList ID="cbl1" runat="server" ValidationGroup="Table1">
                    <asp:ListItem>Option 1</asp:ListItem>
                    <asp:ListItem>Option 2</asp:ListItem>
                </asp:CheckBoxList>
                <small>A small description of the field</small>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow CssClass="Group">
            <asp:TableCell ColumnSpan="2">
                            <div>Group 2</div>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Label ID="Label2" runat="server">DateTimePicker</asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <mits:DatePicker ID="dtp1" runat="server" Required="True" Type="DateTimePicker" ValidationGroup="Table1" />
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow CssClass="Button">
            <asp:TableCell></asp:TableCell>
            <asp:TableCell>
                <asp:Button ID="SaveButton" runat="server" Text="Save Organization" ValidationGroup="Table1" /><asp:Literal
                    ID="ButtonsSeparator" runat="server">&nbsp;&nbsp;or&nbsp;&nbsp;</asp:Literal><asp:LinkButton
                        ID="LinkButton1" runat="server" Text="Save & Close" ValidationGroup="Table1" /><asp:Literal
                            ID="Literal1" runat="server">&nbsp;&nbsp;or&nbsp;&nbsp;</asp:Literal><asp:LinkButton
                                ID="CancelButton" runat="server" CssClass="Cancel" CausesValidation="false" Text="Cancel"
                                ValidationGroup="Table1" /><asp:Literal ID="Literal2" runat="server">&nbsp;&nbsp;or&nbsp;&nbsp;</asp:Literal><asp:LinkButton
                                    ID="LinkButton2" runat="server" CssClass="Delete" Text="Delete" CausesValidation="false"
                                    ValidationGroup="Table1" />
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow CssClass="Footer">
            <asp:TableCell ColumnSpan="2">FooterText</asp:TableCell>
        </asp:TableRow>
    </asp:Table>
    <%-- <p>
        &nbsp;</p>
        <hr />
        <p>
            This is another Table control that looks like MagicForm
        </p>
        <asp:Table ID="Table1" runat="server" Width="550px">
        <asp:TableHeaderRow TableSection="TableHeader">
            <asp:TableHeaderCell ColumnSpan="2">
                <table cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                        <td>
                            <asp:Literal ID="Literal3" runat="server" Text="Edit Organization"></asp:Literal>
                        </td>
                        <td style="text-align: right;">
                            <asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="http://www.google.com"
                                Target="_blank" Text="Google search"></asp:HyperLink>&nbsp;
                            <asp:LinkButton ID="LinkButton8" runat="server" Text="Show Inactive" CausesValidation="false"
                                OnClick="ShowInactiveButton_Click"></asp:LinkButton>&nbsp;
                            <asp:LinkButton ID="LinkButton9" runat="server" Text="Show Active" CausesValidation="false"
                                OnClick="ShowActiveButton_Click"></asp:LinkButton>
                        </td>
                    </tr>
                </table>
            </asp:TableHeaderCell>
        </asp:TableHeaderRow>
        <asp:TableHeaderRow>
            <asp:TableHeaderCell ColumnSpan="2">
                <asp:Literal ID="Literal4" runat="server" Text="HeaderText"></asp:Literal>
            </asp:TableHeaderCell>
        </asp:TableHeaderRow>
        <asp:TableRow>
            <asp:TableCell Width="120px">
                <asp:Label ID="Label3" runat="server">Standard Form input</asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <mits:TextBox ID="txt1" runat="server" Required="true" Columns="35" ValidationGroup="Table1" />
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow CssClass="Group">
            <asp:TableCell ColumnSpan="2">
                            <div>Group 1</div>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
            </asp:TableCell>
            <asp:TableCell>
                <asp:CheckBox ID="chk1" runat="server" Text="This is a checkbox" />
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Label ID="ddl1lbl" runat="server">DropDown</asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:DropDownList ID="ddl1" runat="server" ValidationGroup="Table1">
                    <asp:ListItem>Option 1</asp:ListItem>
                    <asp:ListItem>Option 2</asp:ListItem>
                </asp:DropDownList>
                Simple text inside form
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Label ID="rbl1lbl" runat="server">Radio button list</asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:RadioButtonList ID="rbl1" runat="server" ValidationGroup="Table1">
                    <asp:ListItem>Option 1</asp:ListItem>
                    <asp:ListItem>Option 2</asp:ListItem>
                </asp:RadioButtonList>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Label ID="Label1" runat="server">Checkbox list</asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:CheckBoxList ID="cbl1" runat="server" ValidationGroup="Table1">
                    <asp:ListItem>Option 1</asp:ListItem>
                    <asp:ListItem>Option 2</asp:ListItem>
                </asp:CheckBoxList>
                <small>A small description of the field</small>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow CssClass="Group">
            <asp:TableCell ColumnSpan="2">
                            <div>Group 2</div>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Label ID="Label2" runat="server">DateTimePicker</asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <mits:DatePicker ID="dtp1" runat="server" Required="True" Type="DateTimePicker" ValidationGroup="Table1" />
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableFooterRow>
            <asp:TableCell></asp:TableCell>
            <asp:TableCell>
                <asp:Button ID="SaveButton" runat="server" Text="Save Organization" ValidationGroup="Table1" /><asp:Literal
                    ID="ButtonsSeparator" runat="server">&nbsp;&nbsp;or&nbsp;&nbsp;</asp:Literal><asp:LinkButton
                        ID="LinkButton1" runat="server" Text="Save & Close" ValidationGroup="Table1" /><asp:Literal
                            ID="Literal1" runat="server">&nbsp;&nbsp;or&nbsp;&nbsp;</asp:Literal><asp:LinkButton
                                ID="CancelButton" runat="server" CssClass="Cancel" CausesValidation="false" Text="Cancel"
                                ValidationGroup="Table1" /><asp:Literal ID="Literal2" runat="server">&nbsp;&nbsp;or&nbsp;&nbsp;</asp:Literal><asp:LinkButton
                                    ID="LinkButton2" runat="server" CssClass="Delete" Text="Delete" CausesValidation="false"
                                    ValidationGroup="Table1" />
            </asp:TableCell>
        </asp:TableFooterRow>
        <asp:TableFooterRow TableSection="TableFooter">
            <asp:TableCell ColumnSpan="2">FooterText</asp:TableCell>
        </asp:TableFooterRow>
    </asp:Table>--%>
    <p>
        &nbsp;</p>
    <hr />
    <p>
        This is HtmlTable control that looks like MagicForm
    </p>
    <table id="Table2" runat="server" width="550px">
        <tr class="Caption">
            <td colspan="2">
                <table cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                        <td>
                            <asp:Literal ID="Literal5" runat="server" Text="Edit Organization"></asp:Literal>
                        </td>
                        <td style="text-align: right;">
                            <asp:HyperLink ID="HyperLink3" runat="server" NavigateUrl="http://www.google.com"
                                Target="_blank" Text="Google search"></asp:HyperLink>&nbsp;
                            <asp:LinkButton ID="LinkButton3" runat="server" Text="Show Inactive" CausesValidation="false"
                                OnClick="ShowInactiveButton_Click"></asp:LinkButton>&nbsp;
                            <asp:LinkButton ID="LinkButton4" runat="server" Text="Show Active" CausesValidation="false"
                                OnClick="ShowActiveButton_Click"></asp:LinkButton>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr class="Header">
            <th colspan="2">
                <asp:Literal ID="Literal6" runat="server" Text="HeaderText"></asp:Literal>
            </th>
        </tr>
        <tr>
            <td width="120px">
                <asp:Label ID="Label4" runat="server">Standard Form input</asp:Label>
            </td>
            <td>
                <mits:TextBox ID="TextBox1" runat="server" Required="true" Columns="35" ValidationGroup="Table2" />
            </td>
        </tr>
        <tr class="Group">
            <td colspan="2">
                <div>
                    Group 1</div>
            </td>
        </tr>
        <tr>
            <td>
            </td>
            <td>
                <asp:CheckBox ID="CheckBox1" runat="server" Text="This is a checkbox" />
            </td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="Label5" runat="server">DropDown</asp:Label>
            </td>
            <td>
                <asp:DropDownList ID="DropDownList2" runat="server" ValidationGroup="Table2">
                    <asp:ListItem>Option 1</asp:ListItem>
                    <asp:ListItem>Option 2</asp:ListItem>
                </asp:DropDownList>
                Simple text inside form
            </td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="Label6" runat="server">Radio button list</asp:Label>
            </td>
            <td>
                <asp:RadioButtonList ID="RadioButtonList1" runat="server" ValidationGroup="Table2">
                    <asp:ListItem>Option 1</asp:ListItem>
                    <asp:ListItem>Option 2</asp:ListItem>
                </asp:RadioButtonList>
            </td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="Label7" runat="server">Checkbox list</asp:Label>
            </td>
            <td>
                <asp:CheckBoxList ID="CheckBoxList1" runat="server" ValidationGroup="Table2">
                    <asp:ListItem>Option 1</asp:ListItem>
                    <asp:ListItem>Option 2</asp:ListItem>
                </asp:CheckBoxList>
                <small>A small description of the field</small>
            </td>
        </tr>
        <tr class="Group">
            <td colspan="2">
                <div>
                    Group 2</div>
            </td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="Label8" runat="server">DateTimePicker</asp:Label>
            </td>
            <td>
                <mits:DatePicker ID="DatePicker1" runat="server" Required="True" Type="DateTimePicker"
                    ValidationGroup="Table2" />
            </td>
        </tr>
        <tr class="Button">
            <td>
            </td>
            <td>
                <asp:Button ID="Button1" runat="server" Text="Save Organization" ValidationGroup="Table2" /><asp:Literal
                    ID="Literal7" runat="server">&nbsp;&nbsp;or&nbsp;&nbsp;</asp:Literal><asp:LinkButton
                        ID="LinkButton5" runat="server" Text="Save & Close" ValidationGroup="Table2" /><asp:Literal
                            ID="Literal8" runat="server">&nbsp;&nbsp;or&nbsp;&nbsp;</asp:Literal><asp:LinkButton
                                ID="LinkButton6" runat="server" CssClass="Cancel" CausesValidation="false" Text="Cancel"
                                ValidationGroup="Table2" /><asp:Literal ID="Literal9" runat="server">&nbsp;&nbsp;or&nbsp;&nbsp;</asp:Literal><asp:LinkButton
                                    ID="LinkButton7" runat="server" CssClass="Delete" Text="Delete" CausesValidation="false"
                                    ValidationGroup="Table2" />
            </td>
        </tr>
        <tr class="Footer">
            <td colspan="2">
                FooterText
            </td>
        </tr>
    </table>
</asp:Content>
