-- Insert statements for upgrade the database here
BEGIN TRANSACTION

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, QUOTED_IDENTIFIER, CONCAT_NULL_YIELDS_NULL ON
SET NUMERIC_ROUNDABORT OFF

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	INSERT INTO dbo.Mc_GroupsDepartmentsActions (GroupId, DepartmentId, ActionId, Enabled)
	SELECT GroupId, DepartmentId, 300, Enabled FROM dbo.Mc_GroupsDepartmentsActions WHERE ActionId = 8

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	DELETE FROM dbo.Mc_GroupsDepartmentsActions WHERE ActionId = 8

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
   COMMIT TRANSACTION