//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class BwdUserSidePage {
    
    /// <summary>
    /// Hello1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Micajah.Common.WebControls.Hello Hello1;
    
    /// <summary>
    /// DetailMenu1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Micajah.Common.WebControls.DetailMenu DetailMenu1;
    
    /// <summary>
    /// Master property.
    /// </summary>
    /// <remarks>
    /// Auto-generated property.
    /// </remarks>
    public new Micajah.Common.Pages.MasterPage Master {
        get {
            return ((Micajah.Common.Pages.MasterPage)(base.Master));
        }
    }
}
