using System;
using System.Web.UI.WebControls;
using Micajah.Common.Bll;
using Micajah.Common.Bll.Providers;
using Micajah.Common.Configuration;
using Micajah.Common.Properties;
using Micajah.Common.Security;
using Micajah.Common.WebControls.SetupControls;

namespace Micajah.Common.WebControls.AdminControls
{
    /// <summary>
    /// The control to manage LdapLogs.
    /// </summary>
    public class LdapLogsControl : BaseControl
    {
        #region Members

        private UserContext m_UserContext;

        #endregion
        
        #region Overriden Methods

        protected override void ListInitialize()
        {
            base.ListInitialize();

            List.AutoGenerateEditButton = false;
            List.AutoGenerateDeleteButton = false;
            List.ShowAddLink = false;
        }

        protected override void LoadResources()
        {
            base.LoadResources();
            List.Columns[0].HeaderText = Resources.LdapLogsControl_List_CreatedTimeColumn_HeaderText;
            List.Columns[1].HeaderText = Resources.LdapLogsControl_List_MessageColumn_HeaderText;
            List.Columns[2].HeaderText = Resources.LdapLogsControl_List_IsErrorColumn_HeaderText;
        }

        protected override void OnInit(EventArgs e)
        {
            m_UserContext = UserContext.Current;

            base.OnInit(e);
        }

        #endregion

        #region Protected Methods

        protected void List_DataBound(object sender, EventArgs e)
        {
            if (!this.IsPostBack)
            {
                if (string.IsNullOrEmpty(List.SortExpression))
                    List.Sort("CreatedTime", SortDirection.Descending);
            }
        }

        #endregion
    }
}

