using System;
using Micajah.Common.Application;
using Micajah.Common.Properties;
using Micajah.Common.WebControls.SetupControls;
using Micajah.Common.Bll.Providers;

namespace Micajah.Common.WebControls.AdminControls
{
    public class RulesEngineControl : BaseControl
    {
        #region Overriden Methods

        protected override void LoadResources()
        {
            base.LoadResources();
            HyperLinkField field = (List.Columns[0] as HyperLinkField);
            if (field != null)
            {
                field.Text = Resources.RulesControl_List_Caption;
                field.DataNavigateUrlFormatString = CustomUrlProvider.CreateApplicationAbsoluteUrl(ResourceProvider.VirtualRootShortPath + "admin/rules.aspx?RuleEngineId={0:N}");
            }
        }

        protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);

            Micajah.Common.Pages.MasterPage.InitializeAdminPage(this.Page);

            List.AutoGenerateEditButton = false;
            List.AutoGenerateDeleteButton = false;
            List.ShowAddLink = false;
        }

        #endregion
    }
}
