using Micajah.Common.Bll;
using Micajah.Common.Bll.Providers;
using Micajah.Common.Configuration;
using Micajah.Common.Properties;
using Micajah.Common.Security;
using System;
using System.Web;
using System.Web.UI.WebControls;

namespace Micajah.Common.WebControls.AdminControls
{
    public class CustomStyleSheetEditControl : Micajah.Common.WebControls.SetupControls.MasterControl
    {
        #region Members

        protected Table FormTable;
        protected Literal CaptionLiteral;
        protected System.Web.UI.WebControls.TextBox StyleSheetText;
        protected Button UpdateButton;
        protected PlaceHolder ButtonsSeparator;
        protected HyperLink CancelLink;

        private bool m_IsModernTheme;

        #endregion

        #region Private Methods

        private void LoadResources()
        {
            CaptionLiteral.Text = MagicForm.GetCaption(DetailsViewMode.Edit, Resources.CustomStyleSheetEditControl_FormTable_ObjectName);
            UpdateButton.Text = MagicForm.GetUpdateButtonText(DetailsViewMode.Edit, Resources.CustomStyleSheetEditControl_FormTable_ObjectName, InsertButtonCaptionType.Create, UpdateButtonCaptionType.Save, CloseButtonVisibilityMode.None);
            CancelLink.Text = Resources.AutoGeneratedButtonsField_CancelButton_Text;
        }

        #endregion

        #region Protected Methods

        protected void Page_Load(object sender, EventArgs e)
        {
            Micajah.Common.Pages.MasterPage.InitializeAdminPage(this.Page);

            m_IsModernTheme = (FrameworkConfiguration.Current.WebApplication.MasterPage.Theme == Pages.MasterPageTheme.Modern);

            MagicForm.ApplyStyle(FormTable);

            if (!IsPostBack)
            {
                LoadResources();

                UserContext user = UserContext.Current;
                if (user != null)
                {
                    Organization org = user.SelectedOrganization;
                    if (org != null)
                    {
                        if (!string.IsNullOrEmpty(org.CustomStyleSheet)) StyleSheetText.Text = HttpUtility.HtmlDecode(org.CustomStyleSheet);
                    }
                }

                Micajah.Common.Bll.Action action = ActionProvider.PagesAndControls.FindByActionId(ActionProvider.ConfigurationPageActionId);
                if (action != null)
                    CancelLink.NavigateUrl = action.CustomAbsoluteNavigateUrl;
            }

            if (m_IsModernTheme)
                CancelLink.Visible = false;
            else
                AutoGeneratedButtonsField.InsertButtonSeparator(ButtonsSeparator);
        }

        protected void UpdateButton_Click(object sender, EventArgs e)
        {
            UserContext user = UserContext.Current;
            if (user != null)
            {
                Organization org = user.SelectedOrganization;
                if (org != null)
                {
                    org.CustomStyleSheet = HttpUtility.HtmlEncode(StyleSheetText.Text);

                    if (m_IsModernTheme)
                    {
                        if (this.MasterPage != null)
                        {
                            this.MasterPage.MessageType = NoticeMessageType.Success;
                            this.MasterPage.Message = Resources.BaseEditFormControl_SuccessMessage;
                        }
                    }
                }
            }
        }

        #endregion
    }
}
