using System;
using System.Web.UI;
using System.Web.UI.WebControls;
using Micajah.Common.Bll;
using Micajah.Common.Bll.Providers;
using Micajah.Common.Properties;

namespace Micajah.Common.WebControls.AdminControls
{
    public class UserOrganizationControl : UserControl
    {
        #region Members

        protected Table MagicFormTable;
        protected EntityTreeView Tree;
        protected Label SaveLabel;
        protected Button SaveButton;
        protected LinkButton CancelButton;
        protected PlaceHolder ButtonsSeparator;
        private Guid? m_UserId;

        #endregion

        #region Private Properties

        public Guid UserId
        {
            get
            {
                if (!m_UserId.HasValue)
                {
                    object obj = Support.ConvertStringToType(this.Request.QueryString["objectid"], typeof(Guid));
                    m_UserId = ((obj == null) ? Guid.Empty : (Guid)obj);
                }
                return m_UserId.Value;
            }
        }

        #endregion

        #region Protected Methods

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                Tree.EntityNodeId = UserId;
                Tree.LoadTree();
            }

            SaveButton.Text = string.Concat(Resources.AutoGeneratedButtonsField_SaveButton_Text, Resources.AutoGeneratedButtonsField_CloseButtonSeparator, Resources.AutoGeneratedButtonsField_CloseButton_Text);
            CancelButton.Text = Resources.AutoGeneratedButtonsField_CancelButton_Text;
            AutoGeneratedButtonsField.InsertButtonSeparator(ButtonsSeparator);

            MagicForm.ApplyStyle(MagicFormTable);
        }

        protected void SaveButton_Click(object sender, EventArgs e)
        {
            Tree.SaveTree();
            Response.Redirect(ResourceProvider.UsersPageVirtualPath);
        }

        protected void CancelButton_Click(object sender, EventArgs e)
        {
            Response.Redirect(ResourceProvider.UsersPageVirtualPath);
        }

        #endregion
    }
}
