BEGIN TRANSACTION
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, QUOTED_IDENTIFIER, CONCAT_NULL_YIELDS_NULL ON
SET NUMERIC_ROUNDABORT OFF

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
	EXEC('ALTER PROCEDURE [dbo].[Mc_DeleteViewState]
(
    @Now datetime
)
AS
BEGIN
    SET NOCOUNT ON;
 
	DECLARE @ExpiredViewState TABLE 
	(
		ViewStateId uniqueidentifier NOT NULL
		PRIMARY KEY
	)
 
	INSERT @ExpiredViewState (ViewStateId)
	SELECT ViewStateId
	FROM dbo.Mc_ViewState
	WHERE ExpirationTime < @Now
 
	DECLARE ViewStateCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY
	FOR SELECT ViewStateId FROM @ExpiredViewState ORDER BY CHECKSUM(NEWID())
 
	DECLARE @ViewStateId uniqueidentifier
 
	OPEN ViewStateCursor

	FETCH NEXT FROM ViewStateCursor INTO @ViewStateId
	WHILE @@FETCH_STATUS = 0 BEGIN
		DELETE FROM dbo.Mc_ViewState
		WHERE ViewStateId = @ViewStateId

		FETCH NEXT FROM ViewStateCursor INTO @ViewStateId
	END

	CLOSE ViewStateCursor
	DEALLOCATE ViewStateCursor
END
')

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION

IF @@TRANCOUNT = 1
   COMMIT TRANSACTION