BEGIN TRANSACTION

SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, QUOTED_IDENTIFIER, CONCAT_NULL_YIELDS_NULL, XACT_ABORT ON

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION
   
IF @@TRANCOUNT = 1   
	SET NUMERIC_ROUNDABORT OFF

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION
   
IF @@TRANCOUNT = 1 
	UPDATE [dbo].[Mc_Action] SET [Name] = N'Tree Node Types', [Description] = N'Manage the Tree Node Types' WHERE [ActionId] = '0F6731D3-EE3A-4614-9092-043E088CC3F2'

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION
   
IF @@TRANCOUNT = 1 
	UPDATE [dbo].[Mc_Action] SET [Description] = N'Node Types' WHERE [ActionId] = '8375FC0A-4A82-46F1-B9D8-E53918E4FB42'

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION
   
IF @@TRANCOUNT = 1 
	UPDATE [dbo].[Mc_Action] SET [Name] = N'Tree Node Types', [Description] = N'Manage the Tree Node Types' WHERE [ActionId] = 'CA150872-16A6-4769-8CB9-1195B267A613'

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION
   
IF @@TRANCOUNT = 1 
	UPDATE [dbo].[Mc_Action] SET [Name] = N'Tree Node Types', [Description] = N'Manage the Tree Node Types' WHERE [ActionId] = 'D934D126-F53A-49F0-833C-1C660EBC7894'

IF @@ERROR <> 0
   IF @@TRANCOUNT = 1 ROLLBACK TRANSACTION   

IF @@TRANCOUNT = 1
   COMMIT TRANSACTION